easy_admin:
  entities:
    User:
      class: App\Entity\User
      form: 
        fields:
           - {property: 'email', label: 'Email'}
           - {property: 'username', label: 'Utilisateurs'}
           - {property: 'Roles', type: 'collection'}


      list:
        fields:
            - {property: 'email', label: 'Email'}
            - {property: 'Username', label: 'Utilisateurs'}

        actions:
            - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-primary '}
            - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}